apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sql-explorer.fullname" . }}-secrets
  labels:
    {{- include "sql-explorer.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  ldap-password: {{ .Values.secrets.ldapBindPassword | b64enc | quote }}
  {{- if .Values.secrets.kerberosKeytabBase64 }}
  sql-explorer.keytab: {{ .Values.secrets.kerberosKeytabBase64 | quote }}
  {{- end }}
